#!/bin/sh

ssh ubuntu@ec2-18-217-164-8.us-east-2.compute.amazonaws.com <<EOF

    cd ~/node-aws-app

    git pull

    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh    | bash
    
    . ~/.nvm/nvm.sh
    
    nvm install node
    
    npm install
    
    npm install -g pm2
    
    pm2 restart ecosystem.config.js
    
    exit

EOF